const STORE_IPV4 = "27.121.145.216";
const STORE_IPV6_PREFIX = "2001:f70:9160:600:";
const ADMIN_PIN = "9999";
const EMPLOYEES = {tanaka:{name:"田中",pin:"1234"},sato:{name:"佐藤",pin:"2345"},yamada:{name:"山田",pin:"3456"},oyama:{name:"大山",pin:"4567"}};
function clientIp(request){return request.headers.get("CF-Connecting-IP")||""}
function allowedIp(ip){return ip===STORE_IPV4||ip.startsWith(STORE_IPV6_PREFIX)}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
async function readJson(request){try{return await request.json()}catch{return null}}
function dbRequired(env){return env.DB&&typeof env.DB.prepare==="function"}
async function ensureSchema(env){if(!dbRequired(env))return false;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS employees (id TEXT PRIMARY KEY,name TEXT NOT NULL,pin TEXT NOT NULL,hourly_wage INTEGER NOT NULL DEFAULT 0,transport_allowance INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS punches (id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('in','out')),timestamp TEXT NOT NULL,client_ip TEXT,source TEXT NOT NULL DEFAULT 'web',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS punch_edits (id INTEGER PRIMARY KEY AUTOINCREMENT,punch_id INTEGER,employee_id TEXT NOT NULL,old_type TEXT,old_timestamp TEXT,new_type TEXT,new_timestamp TEXT,reason TEXT NOT NULL,edited_by TEXT NOT NULL,edited_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_punches_employee_time ON punches(employee_id,timestamp)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_punches_time ON punches(timestamp)`).run();for(const [id,e] of Object.entries(EMPLOYEES))await env.DB.prepare(`INSERT OR IGNORE INTO employees (id,name,pin) VALUES (?,?,?)`).bind(id,e.name,e.pin).run();return true}
function adminOk(body){return body?.adminPin===ADMIN_PIN}
async function getEmployees(env,includePrivate=false){await ensureSchema(env);const cols=includePrivate?"id,name,pin,hourly_wage,transport_allowance,active":"id,name";const r=await env.DB.prepare(`SELECT ${cols} FROM employees WHERE active=1 ORDER BY id`).all();return r.results||[]}
export default {async fetch(request,env){const url=new URL(request.url),ip=clientIp(request);if(url.pathname.startsWith("/api/")){if(url.pathname==="/api/network"&&request.method==="GET")return json({ok:true,allowed:allowedIp(ip),clientIp:ip});if(!allowedIp(ip))return json({ok:false,message:"店舗ネットワークからのみ利用できます。"},403);
if(url.pathname==="/api/status"&&request.method==="GET"){try{if(!dbRequired(env))return json({ok:true,version:"1.5.1",database:false,message:"D1未接続です。"});await ensureSchema(env);const r=await env.DB.prepare("SELECT COUNT(*) AS count FROM punches").first(),e=await env.DB.prepare("SELECT COUNT(*) AS count FROM employees WHERE active=1").first();return json({ok:true,version:"1.5.1",database:true,punchCount:Number(r?.count||0),employeeCount:Number(e?.count||0),schema:"ready"})}catch(e){return json({ok:false,message:"D1初期化エラー: "+e.message},500)}}
if(url.pathname==="/api/employees"&&request.method==="GET"){try{return json({ok:true,employees:await getEmployees(env)})}catch(e){return json({ok:false,message:"スタッフ取得エラー: "+e.message},500)}}
if(url.pathname==="/api/auth"&&request.method==="POST"){try{await ensureSchema(env);const b=await readJson(request);if(!b?.employeeId||!/^[0-9]{4}$/.test(b.pin||""))return json({ok:false,message:"PINが違います。"},401);const e=await env.DB.prepare("SELECT id,name FROM employees WHERE id=? AND pin=? AND active=1").bind(b.employeeId,b.pin).first();return e?json({ok:true,employeeId:e.id,name:e.name}):json({ok:false,message:"PINが違います。"},401)}catch(e){return json({ok:false,message:"認証エラー: "+e.message},500)}}
if(url.pathname==="/api/punch"&&request.method==="POST"){try{await ensureSchema(env);const b=await readJson(request);if(!b?.employeeId)return json({ok:false,message:"スタッフが指定されていません。"},400);const e=await env.DB.prepare("SELECT id,name FROM employees WHERE id=? AND active=1").bind(b.employeeId).first();if(!e)return json({ok:false,message:"スタッフが見つかりません。"},400);const last=await env.DB.prepare("SELECT type FROM punches WHERE employee_id=? ORDER BY id DESC LIMIT 1").bind(e.id).first();const type=last?.type==="in"?"out":"in",timestamp=new Date().toISOString();await env.DB.prepare("INSERT INTO punches (employee_id,name,type,timestamp,client_ip) VALUES (?,?,?,?,?)").bind(e.id,e.name,type,timestamp,ip).run();return json({ok:true,type,timestamp,employeeId:e.id})}catch(e){return json({ok:false,message:"打刻保存エラー: "+e.message},500)}}
if(url.pathname==="/api/history"&&request.method==="GET"){try{await ensureSchema(env);const limit=Math.min(Math.max(Number(url.searchParams.get("limit")||30),1),200),id=url.searchParams.get("employeeId");const r=id?await env.DB.prepare("SELECT id,employee_id,name,type,timestamp,client_ip FROM punches WHERE employee_id=? ORDER BY id DESC LIMIT ?").bind(id,limit).all():await env.DB.prepare("SELECT id,employee_id,name,type,timestamp,client_ip FROM punches ORDER BY id DESC LIMIT ?").bind(limit).all();return json({ok:true,rows:r.results||[]})}catch(e){return json({ok:false,message:"履歴取得エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/auth"&&request.method==="POST"){const b=await readJson(request);return adminOk(b)?json({ok:true}):json({ok:false,message:"管理者PINが違います。"},401)}
if(url.pathname==="/api/admin/punches"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const r=await env.DB.prepare("SELECT id,employee_id,name,type,timestamp,client_ip,created_at FROM punches ORDER BY id DESC LIMIT 100").all();return json({ok:true,rows:r.results||[]})}catch(e){return json({ok:false,message:"管理履歴取得エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/edit-history"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const r=await env.DB.prepare("SELECT id,punch_id,employee_id,old_type,old_timestamp,new_type,new_timestamp,reason,edited_by,edited_at FROM punch_edits ORDER BY id DESC LIMIT 100").all();return json({ok:true,rows:r.results||[]})}catch(e){return json({ok:false,message:"修正履歴取得エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/punch-edit"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const id=Number.parseInt(String(b?.punchId??b?.id??""),10),nt=b?.newType,ts=b?.newTimestamp,reason=String(b?.reason||"").trim(),by=String(b?.editedBy||"管理者").trim().slice(0,50);if(!Number.isInteger(id)||id<=0||!["in","out"].includes(nt)||!ts||Number.isNaN(Date.parse(ts))||!reason)return json({ok:false,message:"修正内容が不正です。"},400);const old=await env.DB.prepare("SELECT id,employee_id,type,timestamp FROM punches WHERE id=?").bind(id).first();if(!old)return json({ok:false,message:"打刻が見つかりません。"},404);await env.DB.prepare("UPDATE punches SET type=?,timestamp=? WHERE id=?").bind(nt,ts,id).run();await env.DB.prepare("INSERT INTO punch_edits (punch_id,employee_id,old_type,old_timestamp,new_type,new_timestamp,reason,edited_by) VALUES (?,?,?,?,?,?,?,?)").bind(id,old.employee_id,old.type,old.timestamp,nt,ts,reason,by).run();return json({ok:true,message:"打刻を修正しました。"})}catch(e){return json({ok:false,message:"打刻修正エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/employees"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);return json({ok:true,employees:await getEmployees(env,true)})}catch(e){return json({ok:false,message:"スタッフ管理情報取得エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/employee-create"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const name=String(b?.name||"").trim().slice(0,50),pin=String(b?.pin||"").trim(),wage=Math.max(0,Math.floor(Number(b?.hourlyWage||0))),transport=Math.max(0,Math.floor(Number(b?.transportAllowance||0)));if(!name)return json({ok:false,message:"名前を入力してください。"},400);if(!/^[0-9]{4}$/.test(pin))return json({ok:false,message:"PINは4桁の数字で入力してください。"},400);const dup=await env.DB.prepare("SELECT id FROM employees WHERE pin=? AND active=1").bind(pin).first();if(dup)return json({ok:false,message:"そのPINは既に使用されています。"},400);const id="staff_"+crypto.randomUUID().replace(/-/g,"").slice(0,16);await env.DB.prepare("INSERT INTO employees (id,name,pin,hourly_wage,transport_allowance,active) VALUES (?,?,?,?,?,1)").bind(id,name,pin,wage,transport).run();return json({ok:true,message:name+"さんを追加しました。",id})}catch(e){return json({ok:false,message:"スタッフ追加エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/employee-delete"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const id=String(b?.id||"").trim();const e=await env.DB.prepare("SELECT id,name FROM employees WHERE id=? AND active=1").bind(id).first();if(!e)return json({ok:false,message:"スタッフが見つかりません。"},404);await env.DB.prepare("UPDATE employees SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();return json({ok:true,message:e.name+"さんを削除しました。打刻履歴は保持されています。"})}catch(e){return json({ok:false,message:"スタッフ削除エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/employee-update"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const id=String(b?.id||""),name=String(b?.name||"").trim().slice(0,50),wage=Math.max(0,Math.floor(Number(b?.hourlyWage||0))),transport=Math.max(0,Math.floor(Number(b?.transportAllowance||0))),pin=String(b?.pin||"");if(!id||!name)return json({ok:false,message:"スタッフIDまたは名前がありません。"},400);if(pin&&!/^[0-9]{4}$/.test(pin))return json({ok:false,message:"PINは4桁の数字です。"},400);if(pin)await env.DB.prepare("UPDATE employees SET name=?,hourly_wage=?,transport_allowance=?,pin=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,wage,transport,pin,id).run();else await env.DB.prepare("UPDATE employees SET name=?,hourly_wage=?,transport_allowance=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,wage,transport,id).run();await env.DB.prepare("UPDATE punches SET name=? WHERE employee_id=?").bind(name,id).run();return json({ok:true,message:"スタッフ情報を保存しました。"})}catch(e){return json({ok:false,message:"スタッフ情報保存エラー: "+e.message},500)}}
if(url.pathname==="/api/admin/payroll"&&request.method==="POST"){try{const b=await readJson(request);if(!adminOk(b))return json({ok:false,message:"管理者PINが違います。"},401);await ensureSchema(env);const month=String(b?.month||"");if(!/^\d{4}-\d{2}$/.test(month))return json({ok:false,message:"対象月が不正です。"},400);const [y,m]=month.split("-").map(Number),startLocal=new Date(`${month}-01T00:00:00+09:00`),endLocal=new Date(Date.UTC(y,m,1)-9*60*60*1000),start=new Date(startLocal.getTime()-48*60*60*1000).toISOString(),end=new Date(endLocal.getTime()+48*60*60*1000).toISOString(),startMs=startLocal.getTime(),endMs=endLocal.getTime();const emps=await env.DB.prepare("SELECT id,name,hourly_wage,transport_allowance FROM employees WHERE active=1 ORDER BY id").all(),p=await env.DB.prepare("SELECT employee_id,type,timestamp FROM punches WHERE timestamp>=? AND timestamp<? ORDER BY employee_id,id").bind(start,end).all(),map=new Map((emps.results||[]).map(e=>[e.id,{employeeId:e.id,name:e.name,hourlyWage:Number(e.hourly_wage||0),transportAllowance:Number(e.transport_allowance||0),workDays:0,minutes:0,wage:0,transport:0,total:0,incomplete:false}])),groups=new Map();for(const x of p.results||[]){if(!groups.has(x.employee_id))groups.set(x.employee_id,[]);groups.get(x.employee_id).push(x)}for(const [id,list] of groups){const row=map.get(id);if(!row)continue;let open=null;for(const x of list){if(x.type==="in"){if(!open)open=x}else if(x.type==="out"&&open){const ms=Date.parse(x.timestamp)-Date.parse(open.timestamp),ins=Date.parse(open.timestamp);if(ms>=0&&ins>=startMs&&ins<endMs){row.minutes+=Math.round(ms/60000);row.workDays++}open=null}}if(open)row.incomplete=true}for(const r of map.values()){r.wage=Math.floor(r.minutes*r.hourlyWage/60);r.transport=r.workDays*r.transportAllowance;r.total=r.wage+r.transport}return json({ok:true,version:"1.5.1",month,rows:[...map.values()]})}catch(e){return json({ok:false,message:"給与計算エラー: "+e.message},500)}}
return json({ok:false,message:"Not Found"},404)}
if(url.pathname==="/"||url.pathname==="/index.html"){const asset=await env.ASSETS.fetch(request);if(!asset.ok)return asset;let html=await asset.text();html=html.replace(/V1\.5(?!\.\d)/g,"V1.5.1");return new Response(html,{status:asset.status,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-KNOT-Version":"1.5.1"}})}return env.ASSETS.fetch(request)}};