const STORE_IPV4 = "27.121.145.216";
const STORE_IPV6_PREFIX = "2001:f70:9160:600:";
const RATE_LIMIT_MAX = 5;
const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
const PUNCH_DEBOUNCE_MS = 3000;
function clientIp(request){return request.headers.get("CF-Connecting-IP")||""}
function allowedIp(ip){return ip===STORE_IPV4||ip.startsWith(STORE_IPV6_PREFIX)}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
async function readJson(request){try{return await request.json()}catch{return null}}
function dbRequired(env){return env.DB&&typeof env.DB.prepare==="function"}
async function ensureSchema(env){if(!dbRequired(env))return false;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS employees (id TEXT PRIMARY KEY,name TEXT NOT NULL,pin TEXT NOT NULL,hourly_wage INTEGER NOT NULL DEFAULT 0,transport_allowance INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS punches (id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('in','out')),timestamp TEXT NOT NULL,client_ip TEXT,source TEXT NOT NULL DEFAULT 'web',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS punch_edits (id INTEGER PRIMARY KEY AUTOINCREMENT,punch_id INTEGER,employee_id TEXT NOT NULL,old_type TEXT,old_timestamp TEXT,new_type TEXT,new_timestamp TEXT,reason TEXT NOT NULL,edited_by TEXT NOT NULL,edited_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS login_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT,scope TEXT NOT NULL,key TEXT NOT NULL,ip TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_punches_employee_time ON punches(employee_id,timestamp)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_punches_time ON punches(timestamp)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_login_attempts_scope_key_time ON login_attempts(scope,key,created_at)`).run();return true}
function timingSafeEqual(a,b){const enc=new TextEncoder(),ab=enc.encode(String(a)),bb=enc.encode(String(b));if(ab.length!==bb.length){let dummy=0;for(let i=0;i<ab.length;i++)dummy|=ab[i]^ab[i];return false}let diff=0;for(let i=0;i<ab.length;i++)diff|=ab[i]^bb[i];return diff===0}
function adminOk(body,env){const configured=env&&env.ADMIN_PIN;if(!configured)return false;return timingSafeEqual(String(body?.adminPin||""),String(configured))}
async function checkRateLimit(env,scope,key){const windowStart=new Date(Date.now()-RATE_LIMIT_WINDOW_MS).toISOString();const r=await env.DB.prepare("SELECT COUNT(*) AS count FROM login_attempts WHERE scope=? AND key=? AND created_at>=?").bind(scope,key,windowStart).first();return Number(r?.count||0)}
async function recordFailedAttempt(env,scope,key,ip){await env.DB.prepare("INSERT INTO login_attempts (scope,key,ip) VALUES (?,?,?)").bind(scope,key,ip||"").run()}
async function clearAttempts(env,scope,key){await env.DB.prepare("DELETE FROM login_attempts WHERE scope=? AND key=?").bind(scope,key).run()}
async function requireAdmin(env,body,ip){await ensureSchema(env);const attempts=await checkRateLimit(env,"admin","admin");if(attempts>=RATE_LIMIT_MAX)return{ok:false,status:429,message:"管理者認証の試行回数が多すぎます。しばらく待ってから再度お試しください。"};if(!adminOk(body,env)){await recordFailedAttempt(env,"admin","admin",ip);return{ok:false,status:401,message:"管理者PINが違います。"}}await clearAttempts(env,"admin","admin");return{ok:true}}
async function getEmployees(env,includePrivate=false){await ensureSchema(env);const cols=includePrivate?"id,name,pin,hourly_wage,transport_allowance,active":"id,name";const r=await env.DB.prepare(`SELECT ${cols} FROM employees WHERE active=1 ORDER BY id`).all();return r.results||[]}
export default {async fetch(request,env){const url=new URL(request.url),ip=clientIp(request);if(url.pathname.startsWith("/api/")){if(url.pathname==="/api/network"&&request.method==="GET")return json({ok:true,allowed:allowedIp(ip),clientIp:ip});
if(url.pathname==="/api/status"&&request.method==="GET"){try{if(!dbRequired(env))return json({ok:true,version:"1.6.2",database:false,adminPinConfigured:!!(env&&env.ADMIN_PIN),message:"D1未接続です。"});await ensureSchema(env);const r=await env.DB.prepare("SELECT COUNT(*) AS count FROM punches").first(),e=await env.DB.prepare("SELECT COUNT(*) AS count FROM employees WHERE active=1").first();return json({ok:true,version:"1.6.2",database:true,adminPinConfigured:!!(env&&env.ADMIN_PIN),punchCount:Number(r?.count||0),employeeCount:Number(e?.count||0),schema:"ready"})}catch(err){console.error(err);return json({ok:false,message:"D1初期化でエラーが発生しました。"},500)}}
if(url.pathname==="/api/employees"&&request.method==="GET"){try{return json({ok:true,employees:await getEmployees(env)})}catch(err){console.error(err);return json({ok:false,message:"スタッフ取得でエラーが発生しました。"},500)}}
if(url.pathname==="/api/auth"&&request.method==="POST"){try{if(!allowedIp(ip))return json({ok:false,message:"打刻は店舗ネットワークからのみ行えます。"},403);await ensureSchema(env);const b=await readJson(request);if(!b?.employeeId||!/^[0-9]{4}$/.test(b.pin||""))return json({ok:false,message:"PINが違います。"},401);const attempts=await checkRateLimit(env,"employee",b.employeeId);if(attempts>=RATE_LIMIT_MAX)return json({ok:false,message:"試行回数が多すぎます。しばらく待ってから再度お試しください。"},429);const e=await env.DB.prepare("SELECT id,name FROM employees WHERE id=? AND pin=? AND active=1").bind(b.employeeId,b.pin).first();if(!e){await recordFailedAttempt(env,"employee",b.employeeId,ip);return json({ok:false,message:"PINが違います。"},401)}await clearAttempts(env,"employee",b.employeeId);return json({ok:true,employeeId:e.id,name:e.name})}catch(err){console.error(err);return json({ok:false,message:"認証処理でエラーが発生しました。"},500)}}
if(url.pathname==="/api/punch"&&request.method==="POST"){try{if(!allowedIp(ip))return json({ok:false,message:"打刻は店舗ネットワークからのみ行えます。"},403);await ensureSchema(env);const b=await readJson(request);if(!b?.employeeId)return json({ok:false,message:"スタッフが指定されていません。"},400);const e=await env.DB.prepare("SELECT id,name FROM employees WHERE id=? AND active=1").bind(b.employeeId).first();if(!e)return json({ok:false,message:"スタッフが見つかりません。"},400);const last=await env.DB.prepare("SELECT type,timestamp FROM punches WHERE employee_id=? ORDER BY id DESC LIMIT 1").bind(e.id).first();if(last&&(Date.now()-Date.parse(last.timestamp))<PUNCH_DEBOUNCE_MS)return json({ok:false,message:"直前に打刻済みです。少し待ってから再度お試しください。"},429);const type=last?.type==="in"?"out":"in",timestamp=new Date().toISOString();await env.DB.prepare("INSERT INTO punches (employee_id,name,type,timestamp,client_ip) VALUES (?,?,?,?,?)").bind(e.id,e.name,type,timestamp,ip).run();return json({ok:true,type,timestamp,employeeId:e.id})}catch(err){console.error(err);return json({ok:false,message:"打刻保存でエラーが発生しました。"},500)}}
if(url.pathname==="/api/history"&&request.method==="GET"){try{await ensureSchema(env);const limit=Math.min(Math.max(Number(url.searchParams.get("limit")||30),1),200),id=url.searchParams.get("employeeId");const r=id?await env.DB.prepare("SELECT id,employee_id,name,type,timestamp,client_ip FROM punches WHERE employee_id=? ORDER BY id DESC LIMIT ?").bind(id,limit).all():await env.DB.prepare("SELECT id,employee_id,name,type,timestamp,client_ip FROM punches ORDER BY id DESC LIMIT ?").bind(limit).all();return json({ok:true,rows:r.results||[]})}catch(err){console.error(err);return json({ok:false,message:"履歴取得でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/auth"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);return json({ok:true})}catch(err){console.error(err);return json({ok:false,message:"認証処理でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/punches"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const r=await env.DB.prepare("SELECT id,employee_id,name,type,timestamp,client_ip,created_at FROM punches ORDER BY id DESC LIMIT 100").all();return json({ok:true,rows:r.results||[]})}catch(err){console.error(err);return json({ok:false,message:"管理履歴取得でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/edit-history"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const r=await env.DB.prepare("SELECT id,punch_id,employee_id,old_type,old_timestamp,new_type,new_timestamp,reason,edited_by,edited_at FROM punch_edits ORDER BY id DESC LIMIT 100").all();return json({ok:true,rows:r.results||[]})}catch(err){console.error(err);return json({ok:false,message:"修正履歴取得でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/punch-edit"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const id=Number.parseInt(String(b?.punchId??b?.id??""),10),nt=b?.newType,ts=b?.newTimestamp,reason=String(b?.reason||"").trim(),by=String(b?.editedBy||"管理者").trim().slice(0,50);if(!Number.isInteger(id)||id<=0||!["in","out"].includes(nt)||!ts||Number.isNaN(Date.parse(ts))||!reason)return json({ok:false,message:"修正内容が不正です。"},400);const old=await env.DB.prepare("SELECT id,employee_id,type,timestamp FROM punches WHERE id=?").bind(id).first();if(!old)return json({ok:false,message:"打刻が見つかりません。"},404);await env.DB.prepare("UPDATE punches SET type=?,timestamp=? WHERE id=?").bind(nt,ts,id).run();await env.DB.prepare("INSERT INTO punch_edits (punch_id,employee_id,old_type,old_timestamp,new_type,new_timestamp,reason,edited_by) VALUES (?,?,?,?,?,?,?,?)").bind(id,old.employee_id,old.type,old.timestamp,nt,ts,reason,by).run();return json({ok:true,message:"打刻を修正しました。"})}catch(err){console.error(err);return json({ok:false,message:"打刻修正でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/employees"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);return json({ok:true,employees:await getEmployees(env,true)})}catch(err){console.error(err);return json({ok:false,message:"スタッフ管理情報取得でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/employee-create"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const name=String(b?.name||"").trim().slice(0,50),pin=String(b?.pin||"").trim(),wage=Math.max(0,Math.floor(Number(b?.hourlyWage||0))),transport=Math.max(0,Math.floor(Number(b?.transportAllowance||0)));if(!name)return json({ok:false,message:"名前を入力してください。"},400);if(!/^[0-9]{4}$/.test(pin))return json({ok:false,message:"PINは4桁の数字で入力してください。"},400);const dup=await env.DB.prepare("SELECT id FROM employees WHERE pin=? AND active=1").bind(pin).first();if(dup)return json({ok:false,message:"そのPINは既に使用されています。"},400);const id="staff_"+crypto.randomUUID().replace(/-/g,"").slice(0,16);await env.DB.prepare("INSERT INTO employees (id,name,pin,hourly_wage,transport_allowance,active) VALUES (?,?,?,?,?,1)").bind(id,name,pin,wage,transport).run();return json({ok:true,message:name+"さんを追加しました。",id})}catch(err){console.error(err);return json({ok:false,message:"スタッフ追加でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/employee-delete"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const id=String(b?.id||"").trim();const e=await env.DB.prepare("SELECT id,name FROM employees WHERE id=? AND active=1").bind(id).first();if(!e)return json({ok:false,message:"スタッフが見つかりません。"},404);await env.DB.prepare("UPDATE employees SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();return json({ok:true,message:e.name+"さんを削除しました。打刻履歴は保持されています。"})}catch(err){console.error(err);return json({ok:false,message:"スタッフ削除でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/employee-update"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const id=String(b?.id||""),name=String(b?.name||"").trim().slice(0,50),wage=Math.max(0,Math.floor(Number(b?.hourlyWage||0))),transport=Math.max(0,Math.floor(Number(b?.transportAllowance||0))),pin=String(b?.pin||"");if(!id||!name)return json({ok:false,message:"スタッフIDまたは名前がありません。"},400);if(pin&&!/^[0-9]{4}$/.test(pin))return json({ok:false,message:"PINは4桁です。"},400);if(pin)await env.DB.prepare("UPDATE employees SET name=?,hourly_wage=?,transport_allowance=?,pin=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,wage,transport,pin,id).run();else await env.DB.prepare("UPDATE employees SET name=?,hourly_wage=?,transport_allowance=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,wage,transport,id).run();await env.DB.prepare("UPDATE punches SET name=? WHERE employee_id=?").bind(name,id).run();return json({ok:true,message:"スタッフ情報を保存しました。"})}catch(err){console.error(err);return json({ok:false,message:"スタッフ情報保存でエラーが発生しました。"},500)}}
if(url.pathname==="/api/admin/payroll"&&request.method==="POST"){try{const b=await readJson(request);const auth=await requireAdmin(env,b,ip);if(!auth.ok)return json({ok:false,message:auth.message},auth.status);const month=String(b?.month||"");if(!/^\d{4}-\d{2}$/.test(month))return json({ok:false,message:"対象月が不正です。"},400);const [y,m]=month.split("-").map(Number),startLocal=new Date(`${month}-01T00:00:00+09:00`),endLocal=new Date(Date.UTC(y,m,1)-9*60*60*1000),start=new Date(startLocal.getTime()-48*60*60*1000).toISOString(),end=new Date(endLocal.getTime()+48*60*60*1000).toISOString(),startMs=startLocal.getTime(),endMs=endLocal.getTime();const emps=await env.DB.prepare("SELECT id,name,hourly_wage,transport_allowance FROM employees WHERE active=1 ORDER BY id").all(),p=await env.DB.prepare("SELECT employee_id,type,timestamp FROM punches WHERE timestamp>=? AND timestamp<? ORDER BY employee_id,id").bind(start,end).all(),map=new Map((emps.results||[]).map(e=>[e.id,{employeeId:e.id,name:e.name,hourlyWage:Number(e.hourly_wage||0),transportAllowance:Number(e.transport_allowance||0),workDays:0,minutes:0,wage:0,transport:0,total:0,incomplete:false,days:[]}])),groups=new Map();for(const x of p.results||[]){if(!groups.has(x.employee_id))groups.set(x.employee_id,[]);groups.get(x.employee_id).push(x)}for(const [id,list] of groups){const row=map.get(id);if(!row)continue;let open=null;for(const x of list){if(x.type==="in"){if(!open)open=x}else if(x.type==="out"&&open){const ms=Date.parse(x.timestamp)-Date.parse(open.timestamp),ins=Date.parse(open.timestamp);if(ms>=0&&ins>=startMs&&ins<endMs){const minutes=Math.round(ms/60000);row.minutes+=minutes;row.workDays++;const dateStr=new Date(ins+9*60*60*1000).toISOString().slice(0,10);row.days.push({date:dateStr,in:open.timestamp,out:x.timestamp,minutes,incomplete:false})}open=null}}if(open){const dateStr=new Date(Date.parse(open.timestamp)+9*60*60*1000).toISOString().slice(0,10);row.days.push({date:dateStr,in:open.timestamp,out:null,minutes:0,incomplete:true});row.incomplete=true}}for(const row of map.values())row.days.sort((a,b)=>a.date===b.date?(a.in<b.in?-1:1):(a.date<b.date?-1:1));for(const r of map.values()){r.wage=Math.floor(r.minutes*r.hourlyWage/60);r.transport=r.workDays*r.transportAllowance;r.total=r.wage+r.transport}return json({ok:true,version:"1.6.2",month,rows:[...map.values()]})}catch(err){console.error(err);return json({ok:false,message:"給与計算でエラーが発生しました。"},500)}}
return json({ok:false,message:"Not Found"},404)}
if(url.pathname==="/"||url.pathname==="/index.html"){const asset=await env.ASSETS.fetch(request);if(!asset.ok)return asset;let html=await asset.text();html=html.replace(/V1\.6(?!\.\d)/g,"V1.6.2");return new Response(html,{status:asset.status,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-KNOT-Version":"1.6.2"}})}return env.ASSETS.fetch(request)}};
